import React from 'react';
import BaseFormContainer from '../BaseFormContainer';
import SelectField from '../../../components/form/fields/SelectField';
import PropTypes from 'prop-types';
import HttpMethodEnum from '../../../enum/httpMethodTypeEnum';
import AuthorizationTypeEnum from '../../../enum/authorizationTypeEnum';
import { createMethodApiRequest } from "../../../store/actions/entriesActions";
import { connect } from "react-redux";
import TextField from '@material-ui/core/TextField';
import { omit, keys } from 'lodash';

/**
 *
 */
class RestApiMethodForm extends BaseFormContainer {
    /**
     *
     * @param props
     */
    constructor(props) {
        super(props);
        this.state.data = this.initData({
            httpMethod: '',
            authorizationType: 'NONE',
            authorizerId: ''
        });

        this.constData = {
            httpMethodOptions: HttpMethodEnum,
        };

        const existsHttpMethods = this.props.resource.resourceMethods;
        if (existsHttpMethods) {
            this.constData.httpMethodOptions = omit(this.constData.httpMethodOptions, keys(existsHttpMethods));
        }

        this.setValidationRules({
            httpMethod: {
                presence: {
                    allowEmpty: false
                },
                inclusion: Object.values(this.constData.httpMethodOptions)
            },
            authorizationType: {
                presence: {
                    allowEmpty: false
                },
                inclusion: Object.values(AuthorizationTypeEnum)
            },
            authorizerId: {
                length: {
                    maximum: 250
                }
            }
        });
    }

    /**
     *
     */
    onRequestSuccess = (response) => {
        this.setState({isProcessing: false});
        this.props.onSuccess(response.httpMethod);
    };

    /**
     *
     * @param err
     */
    onRequestError = (err) => {
        this.setState({isProcessing: false});
    };

    /**
     *
     */
    onSubmitValid = () => {
        this.setState({isProcessing: true});
        this.props.actions.createHttpMethod(this.props.accountId, this.props.restApiId, this.props.resource.id, this.state.data, this.onRequestSuccess, this.onRequestError);
    };

    /**
     *
     * @returns {*}
     */
    render() {
        return this.renderForm(
            <React.Fragment>
                <SelectField
                    required
                    options={this.constData.httpMethodOptions}
                    name="httpMethod"
                    label="HTTP method"
                    value={this.state.data.httpMethod}
                    error={Boolean(this.state.errors.httpMethod) ? this.state.errors.httpMethod[0] : ''}
                    onChange={this.handleChange}
                    helperText="Specifies the method request's HTTP method type."
                />

                <SelectField
                    options={AuthorizationTypeEnum}
                    name="authorizationType"
                    label="Authorization Type"
                    value={this.state.data.authorizationType}
                    error={Boolean(this.state.errors.authorizationType) ? this.state.errors.authorizationType[0] : ''}
                    onChange={this.handleChange}
                    helperText="The method's authorization type"
                />

                <TextField
                    label="authorizerId"
                    name="authorizerId"
                    placeholder="Authorizer Id"
                    helperText={Boolean(this.state.errors.path) ? this.state.errors.path[0] : 'Specifies the identifier of an Authorizer to use on this Method, if the type is CUSTOM or COGNITO_USER_POOLS. The authorizer identifier is generated by API Gateway when you created the authorizer'}
                    fullWidth
                    margin="normal"
                    error={Boolean(this.state.errors.authorizerId)}
                    multiline={false}
                    InputLabelProps={{
                        shrink: true,
                    }}
                    onChange={this.handleChange}
                    value={this.state.data.authorizerId}
                />

            </React.Fragment>
        );
    }
}

/**
 *
 * @param {*} dispatch
 */
const mapDispatchToProps = (dispatch) => {
    return {
        actions: {
            createHttpMethod: (accountId, restApiId, resourceId, data, onSuccess = null, onError = null) => dispatch(createMethodApiRequest(accountId, restApiId, resourceId, data, onSuccess, onError)),
        }
    }
};

export default connect(null, mapDispatchToProps)(RestApiMethodForm);

RestApiMethodForm.propTypes = {
    accountId: PropTypes.any.isRequired,
    restApiId: PropTypes.any.isRequired,
    resource: PropTypes.object.isRequired,
    initialData: PropTypes.object,
    isUpdateAction: PropTypes.bool.isRequired,
    entityId: PropTypes.any,
    onSuccess: PropTypes.func.isRequired
};
