// account
export const ACTION_SET_LOADING_ACCOUNT_LIST = 'LOAD_ACOUNT_LIST';
export const ACTION_SET_ACCOUNT_LIST = 'SET_ACCOUNT_LIST';
export const ACTION_SET_ACCOUNT_LOADED = 'SET_ACCOUNT_LOADED';
export const ACTION_SET_ACCOUNT = 'ACTION_SET_ACCOUNT';
export const ACTION_REMOVE_ACCOUNT = 'ACTION_REMOVE_ACCOUNT';

// account settings
export const ACTION_SETTINGS_ACCOUNT_LOAD_ACCOUNT = 'ACTION_SETTINGS_ACCOUNT_LOAD_ACCOUNT';
export const ACTION_SETTINGS_ACCOUNT_SET_ACCOUNT = 'ACTION_SETTINGS_ACCOUNT_SET_ACCOUNT';
export const ACTION_SETTINGS_ACCOUNT_PROCESSING = 'ACTION_SETTINGS_ACCOUNT_PROCESSING';
export const ACTION_SETTINGS_ACCOUNT_PROCESSING_DONE = 'ACTION_SETTINGS_ACCOUNT_PROCESSING_DONE';
export const ACTION_SETTINGS_ACCOUNT_SET_DEFAULT = 'ACTION_SETTINGS_ACCOUNT_SET_DEFAULT';

// api list
export const ACTION_ADD_API = 'ADD_API';
export const ACTION_DELETE_API = 'DELETE_API';
export const ACTION_SET_API_LIST = 'SET_API_LIST';
export const ACTION_UPDATE_API = 'UPDATE_API';

// entries list
export const ACTION_SET_RESOURCE_ENTRIES = 'SET_RESOURCE_ENTRIES';
export const ACTION_DELETE_RESOURCE = 'DELETE_RESOURCE';
export const ACTION_ADD_RESOURCE = 'ADD_RESOURCE';
export const ACTION_PUT_HTTP_METHOD = 'PUT_HTTP_METHOD';
export const ACTION_PUT_INTEGRATION = 'PUT_INTEGRATION';
export const ACTION_PUT_RESPONSE = 'PUT_RESPONSE';
export const ACTION_DELETE_HTTP_METHOD = 'DELETE_HTTP_METHOD';
export const ACTION_SET_VPS_LINKS = 'SET_VPC_LINKS';

export const ACTION_ENTRIES_LOADING_REST_API = 'ACTION_ENTRIES_LOADING_REST_API';
export const ACTION_ENTRIES_SET_REST_API = 'ACTION_ENTRIES_SET_REST_API';

// API actions
export const ACTION_AWS_API_CALL = 'AWS_API_CALL';

// APP params
export const ACTION_SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const ACTION_SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const ACTION_SET_AWS_REGIONS_LIST = 'SET_AWS_REGIONS_LIST';

// NOTIFICATIONS
export const ACTION_ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ACTION_REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const ACTION_FLUSH_NOTIFICATION = 'FLUSH_NOTIFICATION';

// LIST actions
export const ACTION_LIST_LOADING_LAMBDA_FUNCTIONS = 'ACTION_LIST_LOADING_LAMBDA_FUNCTIONS';
export const ACTION_LIST_SET_LAMBDA_FUNCTIONS = 'ACTION_LIST_SET_LAMBDA_FUNCTIONS';

// API Resource detail
export const ACTION_SET_FILTER_VALUE = 'ACTION_SET_FILTER_VALUE';
export const ACTION_SET_FILTERING_STATUS = 'ACTION_SET_FILTERING_STATUS';