// account
export const ACTION_LOAD_ACOUNT_LIST = 'LOAD_ACOUNT_LIST';
export const ACTION_SET_ACCOUNT_LIST = 'SET_ACCOUNT_LIST';
export const ACTION_SET_ACCOUNT_LOADED = 'SET_ACCOUNT_LOADED';
export const ACTION_SET_AUTHENTICATE_REQUEST = 'ACTION_SET_AUTHENTICATE_REQUEST';
export const ACTION_SET_AUTHENTICATE_REQUEST_DONE = 'ACTION_SET_AUTHENTICATE_REQUEST_DONE';
export const ACTION_SET_ACCOUNT = 'ACTION_SET_ACCOUNT';

// api list
export const ACTION_ADD_API = 'ADD_API';
export const ACTION_DELETE_API = 'DELETE_API';
export const ACTION_SET_API_LIST = 'SET_API_LIST';
export const ACTION_UPDATE_API = 'UPDATE_API';
export const ACTION_LOAD_ROUTE_LIST = 'LOAD_ROUTE_LIST';

// entries list
export const ACTION_SET_RESOURCE_ENTRIES = 'SET_RESOURCE_ENTRIES';
export const ACTION_DELETE_RESOURCE = 'DELETE_RESOURCE';
export const ACTION_ADD_RESOURCE = 'ADD_RESOURCE';
export const ACTION_PUT_HTTP_METHOD = 'PUT_HTTP_METHOD';
export const ACTION_PUT_INTEGRATION = 'PUT_INTEGRATION';
export const ACTION_PUT_RESPONSE = 'PUT_RESPONSE';
export const ACTION_DELETE_HTTP_METHOD = 'DELETE_HTTP_METHOD';
export const ACTION_SET_VPS_LINKS = 'SET_VPC_LINKS';


// API actions
export const ACTION_AWS_API_CALL = 'AWS_API_CALL';

// APP params
export const ACTION_SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const ACTION_SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const ACTION_SET_AWS_REGIONS_LIST = 'SET_AWS_REGIONS_LIST';

// NOTIFICATIONS
export const ACTION_ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ACTION_REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const ACTION_FLUSH_NOTIFICATION = 'FLUSH_NOTIFICATION';