version: '2'

services:
  app:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    image: api_gateway_app
    volumes:
      - ./app:/app
    ports:
      - ${PUBLIC_PORT}:3000
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}      # Used for hot reload. Without it hot reload does not work for me
    #  - HOST=${HOST}

  back:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    image: node_app
    volumes:
      - ./back:/app
    ports:
      - ${PUBLIC_NODE_HOST_PORT}:3000
    expose:
      - 3000
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}       # Used for hot reloading. Should be true
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_PORT=${NODE_MONGO_DB_PORT}
      - MONGO_DB_HOST=${NODE_MONGO_DB_HOST}
    command: ["npm", "run", "develop"]

  mongo:
    image: mongo:4.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - ${MONGO_PORT}:27017